#logging.config=config/log4j2.xml


server.port=9393
# 10.72.100.35 Port: 33061
spring.data.mongodb.host=my_database
spring.data.mongodb.database=creants-account
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=root
spring.data.mongodb.password=d4rtness@123
spring.data.mongodb.port=27017


#couchbase
cache.hosts=10.72.100.35
cache.bucket=creants-login
cache.pass=creants
cache.couchbaseOpTimeout=5000
cache.couchbaseConnectionTimeout=10000

#http://stackoverflow.com/questions/34694468/failed-messages-javax-mail-messagingexception-cant-determine-local-email-addr
#http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#common-application-properties
spring.mail.default-encoding=UTF-8
spring.mail.host=mail.creants.net
spring.mail.username=no-reply@creants.net
spring.mail.password=n0r3plycr3@nts
spring.mail.port=587
spring.mail.test-connection=false
spring.mail.properties.mail.smtp.starttls.enable = true

fb.app.id=739616139797120
fb.app.secret=a81f99dd400b8b9d6246e43ca9162317
